import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Phoenix-AI",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/phoenix.png", type: "image/png", sizes: "32x32" },
      { url: "/phoenix.png", type: "image/png", sizes: "16x16" },
    ],
    shortcut: "/phoenix.png",
    apple: "/phoenix.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
